# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
source 'https://github.com/aliyun/aliyun-specs.git'
#source 'https://github.com/CocoaPods/specs.git'
source 'https://cdn.cocoapods.org/'

target 'webviewtest' do
  pod 'Masonry'
end
